// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalBrands.TimeSheet.DAL.Migrations
{
    [DbContext(typeof(TimeSheetDbContext))]
    partial class TimeSheetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalBrands.TimeSheet.DAL.Persistence.Data.Entities.ETask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Task Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Task Category");

                    b.Property<DateTime?>("CompleteTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Task Description");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Task Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Task Title");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Research",
                            Description = "Create ERD and schema",
                            EmployeeId = 1,
                            EndDate = new DateTime(2025, 9, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 9, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Title = "Design DB"
                        },
                        new
                        {
                            Id = 2,
                            Category = "FeatureDevelopment",
                            Description = "Build initial API endpoints",
                            EmployeeId = 1,
                            EndDate = new DateTime(2025, 9, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 9, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Title = "API Setup"
                        },
                        new
                        {
                            Id = 3,
                            Category = "FeatureDevelopment",
                            CompleteTask = new DateTime(2025, 9, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implement product catalog",
                            EmployeeId = 1,
                            EndDate = new DateTime(2025, 9, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2,
                            StartDate = new DateTime(2025, 9, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Title = "Product Module"
                        },
                        new
                        {
                            Id = 4,
                            Category = "FeatureDevelopment",
                            Description = "Implement shopping cart",
                            EmployeeId = 1,
                            EndDate = new DateTime(2025, 9, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2,
                            StartDate = new DateTime(2025, 9, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            Title = "Cart Module"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Testing",
                            Description = "Write unit tests",
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 9, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 9, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Title = "Testing API"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Improvement",
                            CompleteTask = new DateTime(2025, 9, 29, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Check frontend components",
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 9, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            StartDate = new DateTime(2025, 9, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Title = "UI Review"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Testing",
                            Description = "Test payment gateway",
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 9, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2,
                            StartDate = new DateTime(2025, 9, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Title = "Payment Module"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Documentation",
                            Description = "Document found issues",
                            EmployeeId = 2,
                            EndDate = new DateTime(2025, 9, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2,
                            StartDate = new DateTime(2025, 9, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            Title = "Bug Report"
                        });
                });

            modelBuilder.Entity("GlobalBrands.TimeSheet.DAL.Persistence.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Employee Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AzureObjectId")
                        .HasColumnType("int")
                        .HasColumnName("oid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("Employee Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Employee Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            Email = "Ahmedli@example.com",
                            Name = "Ahmed Ali",
                            PhoneNumber = "01012345678",
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Alexandria, Egypt",
                            Email = "sara.mohamed@example.com",
                            Name = "Sara Mohamed",
                            PhoneNumber = "01198765432",
                            Salary = 12000m
                        });
                });

            modelBuilder.Entity("GlobalBrands.TimeSheet.DAL.Persistence.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Project Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project Name");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Internal project to track working hours",
                            Name = "Time Tracking System"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Web platform for online shopping",
                            Name = "E-Commerce Platform"
                        });
                });

            modelBuilder.Entity("GlobalBrands.TimeSheet.DAL.Persistence.Data.Entities.ETask", b =>
                {
                    b.HasOne("GlobalBrands.TimeSheet.DAL.Persistence.Data.Entities.Employee", "Employee")
                        .WithMany("Tasks")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalBrands.TimeSheet.DAL.Persistence.Data.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GlobalBrands.TimeSheet.DAL.Persistence.Data.Entities.Employee", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GlobalBrands.TimeSheet.DAL.Persistence.Data.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
